name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Create ca.pem file from secret
      env:
        DB_CA_CERT: ${{ secrets.DB_CA_CERT }}
      run: echo "${DB_CA_CERT}" > ./ca.pem

    - name: Deploy application
      env: 
        PORT: ${{ secrets.PORT }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_SSL: ${{ secrets.DB_SSL }}
        REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
        CLIENT_ORIGIN: "https://userslist-5pm7t0b1k-olgakrugliks-projects.vercel.app"
      run: |
        echo "Starting application..."
        npm start
